# Generated by Django 3.0 on 2019-12-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=('Activo', 'Activo'), max_length=15),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=('Activo', 'Activo'), max_length=15),
        ),
    ]
