# Generated by Django 3.0 on 2019-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion',
            field=models.TextField(default='...', max_length=100),
        ),
    ]
