# Generated by Django 3.0 on 2019-12-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_auto_20191215_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Reparación', 'Reparación')], default=('Activo', 'Activo'), max_length=15),
        ),
    ]
