# Generated by Django 3.0 on 2019-12-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='status',
            field=models.CharField(choices=[('Prestado', 'Prestado'), ('Entregado', 'Entregado')], default=('Prestado', 'Prestado'), max_length=15),
        ),
    ]
